image: cypress/base:latest

stages:
  - test

test:
  stage: test
  script:
    - yarn install
    - yarn lint
    - yarn build
    - yarn test
  cache:
    key: ${CI_JOB_NAME}
    paths:
      - .yarn
      - node_modules/
  artifacts:
    paths:
      - dist/
