language: node_js
node_js: 10
addons:
  apt:
    packages:
      # Required by cypress
      - libgconf-2-4

cache:
  npm: true
  directories:
    # Required by cypress
    - ~/.cache

install: npm ci

script:
  - npm run lint
  - npm run test
  - npm run build

deploy:
  provider: surge
  skip_cleanup: true
  project: dist
  keep_history: true
  domain: intersect-digital-work-sample-tyler-grinn.surge.sh
  on:
    branch: master
