language: node_js
node_js: 10
addons:
  apt:
    packages:
      # Required by cypress
      - libgconf-2-4

cache:
  yarn: true
  directories:
    # Required by cypress
    - ~/.cache

install: yarn

script:
  - yarn lint
  - yarn test
  - yarn build

deploy:
  provider: surge
  skip_cleanup: true
  project: dist
  keep_history: true
  domain: intersect-digital-work-sample-tyler-grinn.surge.sh
  on:
    branch: master
